sudo: required

services:
  - docker

language: go

go:
  - 1.5.1

before_install:
 - go get github.com/constabulary/gb/...

install: gb vendor restore

script: gb test all

# build docker
after_success:
 - docker build -t gobwas/kursobot .
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" -e="$DOCKER_EMAIL"
 - docker push gobwas/kursobot